### ISSUE TITLE
效果无法复现，距离论文中的内容有差异

### ISSUE THREAD

**Issue by shukhg** [zzhUSTC2016/RAREMed#1]
使用默认参数，分别在 3090服务器 和 A800 服务器，跑的结果为：Jaccard: 0.535, DDI Rate: 0.07008, PRAUC: 0.7925, AVG_F1: 0.6884, AVG_PRC: 0.7429, AVG_RECALL: 0.6630, AVG_MED: 18.07。  想请问下作者应该用什么参数去跑效果比较好？

**Comment by zzhUSTC2016** [comment]
感谢提问！与其他baseline相比如何？数据处理用的哪个版本的代码？

**Comment by shukhg** [comment]
> 感谢提问！与其他baseline相比如何？数据处理用的哪个版本的代码？

数据处理用的最新的代码，应该是 “Version 1.0” 版本。相比于其他 baseline 效果是略优，但仍未达到您论文中写的效果

**Comment by zzhUSTC2016** [comment]
最优的baseline结果是多少？

**Comment by zzhUSTC2016** [comment]
> > 感谢提问！与其他baseline相比如何？数据处理用的哪个版本的代码？
> 
> 数据处理用的最新的代码，应该是 “Version 1.0” 版本。相比于其他 baseline 效果是略优，但仍未达到您论文中写的效果

另外还想问下，处理数据和跑代码的过程中有没有遇到什么困难？

**Comment by shukhg** [comment]
> > > 感谢提问！与其他baseline相比如何？数据处理用的哪个版本的代码？
> > 
> > 
> > 数据处理用的最新的代码，应该是 “Version 1.0” 版本。相比于其他 baseline 效果是略优，但仍未达到您论文中写的效果
> 
> 另外还想问下，处理数据和跑代码的过程中有没有遇到什么困难？

除了  data 下 process.py 需要改为 preprocess.py，没遇到什么问题

**Comment by shukhg** [comment]
> 最优的baseline结果是多少？

我没有跑其他 baseline，我是直接对比你写的论文

**Comment by zzhUSTC2016** [comment]
> > 最优的baseline结果是多少？
> 
> 我没有跑其他 baseline，我是直接对比你写的论文

建议跑一下baseline试试，代码我也都放出来了。不然不好评判。不同实验平台上绝对效果不一样挺正常的。
