### ISSUE TITLE
hell~感谢作者分享优秀的工作，但似乎batch_size只能设置为1？

### ISSUE THREAD

**Issue by 2391134843** [zzhUSTC2016/RAREMed#3]
hell~感谢作者分享优秀的工作，但似乎batch_size只能设置为1？ 
于是我修改了代码：
 # multi_target_dis = np.full((1, voc_size[0]), -1)
 # multi_target_pro = np.full((1, voc_size[1]), -1)
#修改初始化，设置为batch_size，修改为：
multi_target_dis = np.full((batch_size, voc_size[0]), -1)
multi_target_pro = np.full((batch_size, voc_size[1]), -1)
我尝试修改代码，但之后我还发现batch_size大小会影响ja的维度的变化，这样会造成：
方法def get_grouped_metrics(ja, visit_weights, group_num=5): 报错
 weighted_jaccard = np.average(ja, weights=visit_weights)
请问作者在实验的时候考虑了不同的batch_size情况了吗？我应该如何解决呢？ 非常感谢~！

**Comment by zzhUSTC2016** [comment]
细节不太记得了，好像batch size影响不太大，后来没管了。你改batch size是想加速训练吗？

**Comment by zzhUSTC2016** [comment]
感谢关注！

**Comment by 2391134843** [comment]
感谢回复！是的，我想加快训练过程，因为很少看到batch_size设置为1的情况。因为这样gpu利用率太低了，感觉可以加大一点，加快速度，哈哈，那我自己再看看~后续如果我做了相关工作的研究 我会cite论文~再次感谢回复！
